version: 0.2

phases:
  install:
    commands:
      - pip3 install awscli --upgrade --user
      - curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.1 python3 -
      - export PATH=/root/.local/bin:$PATH
  build:
    commands:
      - poetry publish --build