version: 0.2

phases:
  install:
    commands:
      - pip3 install awscli --upgrade --user
      - curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.1 python3 -
      - export PATH=/root/.local/bin:$PATH
      - python3 -m venv env; source env/bin/activate
      - poetry install --with test --sync
  build:
    commands:
      - poetry run python3 -m nose2 -s test -t src