version: 0.2

phases:
  install:
    commands:
      - pip3 install awscli pip --upgrade --user
      - curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.1 python3 -
      - export PATH=/root/.local/bin:$PATH
      - poetry build
      - python3 -m venv env; source env/bin/activate
      - python3 -m pip install nose2 dist/*.whl
  build:
    commands:
      - cd test
      - python3 -m nose2 -s . -t .