version: 0.2

phases:
  install:
    commands:
      - pip3 install awscli --upgrade --user
      - curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.2.1 python3 -
      - export PATH=/root/.local/bin:$PATH
      - poetry build
      - python3 -m venv env; source env/bin/activate
      - pip install nose2 dist/*.whl
  pre_build:
    commands:
      - aws codeartifact login --tool pip --domain w-martin --repository codeartifact
  build:
    commands:
      - poetry run python3 -m nose2 -s test -t .